### ISSUE TITLE
Illegal arguements exception when running deviceDetectionOnPremise

### ISSUE THREAD

**Issue by jwrosewell** [51Degrees/pipeline-node#1]
Using Windows I get the following exception when running the unmodified example deviceDetectionOnPremise.js.

C:\Program Files\nodejs\node.exe --inspect-brk=10803 fiftyone.pipeline.devicedetection\examples\deviceDetectionOnPremise.js
Debugger listening on ws://127.0.0.1:10803/43723415-bcad-4ca7-942e-09538e5832b2
Debugger attached.
d:\Workspace\pipeline-node\fiftyone.pipeline.devicedetection\deviceDetectionOnPremise.js:141
        var engine = new swigWrapper["Engine" + swigWrapperType + "Swig"](dataFile, config, requiredProperties);
                     ^

Error: Illegal arguments for construction of _exports_EnginePatternSwig
    at new deviceDetectionOnPremise (d:\Workspace\pipeline-node\fiftyone.pipeline.devicedetection\deviceDetectionOnPremise.js:141:22)
    at Object.<anonymous> (d:\Workspace\pipeline-node\fiftyone.pipeline.devicedetection\examples\deviceDetectionOnPremise.js:17:14)
    at Module._compile (module.js:649:14)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
Waiting for the debugger to disconnect...
Error: Illegal arguments for construction of _exports_EnginePatternSwig
    at new deviceDetectionOnPremise (d:\Workspace\pipeline-node\fiftyone.pipeline.devicedetection\deviceDetectionOnPremise.js:141:22)
    at Object.<anonymous> (d:\Workspace\pipeline-node\fiftyone.pipeline.devicedetection\examples\deviceDetectionOnPremise.js:17:14)
    at Module._compile (module.js:649:14)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by Steve51D** [comment]
Apologies for the delay in getting back to you.
This issue was resolved with the release of 4.1.0 on 16th Apr 2020
